const Play = {
    HIT: "HIT",
    STAND: "STAND",
    DOUBLE_DOWN: "DOUBLE DOWN",
    SPLIT: "SPLIT",

    DOUBLE_DOWN_OR_HIT: "DOUBLE DOWN OR HIT",
    DOUBLE_DOWN_OR_STAND: "DOUBLE DOWN OR STAND"
}