const Play = {
    HIT: "HIT", 
    STAND: "STAND", 
    DOUBLE_DOWN: "DOUBLE_DOWN",
    SPLIT: "SPLIT",

    DOUBLE_DOWN_OR_HIT: "DOUBLE_DOWN_OR_HIT",
    DOUBLE_DOWN_OR_STAND: "DOUBLE_DOWN_OR_STAND"
}